import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Download, FileJson, Shield, XCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Progress } from "@/components/ui/progress";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { NoirToolShell } from "@/components/layout/NoirToolShell";
import { useAnalysisStore } from "@/lib/analysis-store";
import type { AnalysisRun, RiskLevel } from "@/lib/api";
import { cn } from "@/lib/utils";

interface ComplianceRow {
  algorithm: string;
  nistApproved: boolean;
  fipsReady: boolean;
  deprecated: boolean;
  inUse: boolean;
  riskLevel: RiskLevel;
}

const approvedPatterns = /aes|sha-?2|sha256|sha512|rsa|ecc|ecdsa|ecdh|chacha20|poly1305/i;
const deprecatedPatterns = /md5|sha-?1|des|rc4|xor|lcg|custom/i;

function normalizeLabel(label: string) {
  return label.replace(/_/g, "-").toUpperCase();
}

function buildCompliance(run: AnalysisRun): ComplianceRow[] {
  const labels = run.summary.detectedLabels.length > 0 ? run.summary.detectedLabels : [run.summary.topPrediction];

  return labels.map((label) => {
    const deprecated = deprecatedPatterns.test(label);
    const approved = approvedPatterns.test(label) && !deprecated;
    const proprietary = run.modelType === "proprietary" || /custom|proprietary/i.test(label);

    return {
      algorithm: normalizeLabel(label),
      nistApproved: approved && !proprietary,
      fipsReady: approved && !proprietary,
      deprecated,
      inUse: true,
      riskLevel: deprecated ? "high" : proprietary ? "medium" : approved ? "low" : run.summary.riskLevel,
    };
  });
}

function recommendationsFor(run: AnalysisRun, rows: ComplianceRow[]) {
  const fromModel = run.details.recommendations;
  if (Array.isArray(fromModel) && fromModel.length > 0) {
    return fromModel.map((item, index) => ({
      id: `model-${index}`,
      priority: run.summary.riskLevel === "high" ? "High" : "Medium",
      title: String(item),
      detail: "Generated by the proprietary model response contract.",
    }));
  }

  const recs = rows
    .filter((row) => row.riskLevel !== "low")
    .map((row) => ({
      id: row.algorithm,
      priority: row.riskLevel === "high" ? "High" : "Medium",
      title: `Review ${row.algorithm}`,
      detail: row.deprecated
        ? "Deprecated primitive detected. Replace it with an approved modern primitive."
        : "Signal requires manual review against firmware threat model and key lifecycle.",
    }));

  if (recs.length > 0) {
    return recs;
  }

  return [
    {
      id: "baseline",
      priority: "Low",
      title: "Preserve current baseline",
      detail: "No weak primitive was detected in the latest run. Keep evidence tied to the firmware release.",
    },
  ];
}

function downloadJson(filename: string, value: unknown) {
  const blob = new Blob([JSON.stringify(value, null, 2)], { type: "application/json" });
  const url = window.URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  window.URL.revokeObjectURL(url);
  document.body.removeChild(anchor);
}

function Status({ value, inverted = false }: { value: boolean; inverted?: boolean }) {
  const healthy = inverted ? !value : value;
  return healthy ? (
    <CheckCircle2 className="h-4 w-4 text-emerald-200" />
  ) : (
    <XCircle className="h-4 w-4 text-red-200" />
  );
}

const RiskCompliance = () => {
  const { latestRun, usingDemoData } = useAnalysisStore();
  const [includeEvidence, setIncludeEvidence] = useState(false);

  const rows = useMemo(() => buildCompliance(latestRun), [latestRun]);
  const recommendations = useMemo(() => recommendationsFor(latestRun, rows), [latestRun, rows]);
  const passRate = Math.round((rows.filter((row) => row.riskLevel === "low").length / Math.max(1, rows.length)) * 100);
  const atRisk = rows.filter((row) => row.riskLevel !== "low").length;

  const categories = [
    { label: "Algorithm strength", value: latestRun.summary.riskScore },
    { label: "Protocol fit", value: Math.min(100, latestRun.summary.riskScore + (latestRun.modelType === "proprietary" ? 8 : -10)) },
    { label: "Entropy confidence", value: rows.some((row) => /MD5|XOR|CUSTOM/.test(row.algorithm)) ? 78 : 34 },
    { label: "Evidence completeness", value: includeEvidence ? 42 : 64 },
  ];

  const exportPayload = {
    run: latestRun,
    compliance: rows,
    recommendations,
    includeEvidence,
  };

  return (
    <NoirToolShell
      eyebrow="red room matrix"
      title="Weak crypto gets loud."
      copy="Deprecated primitives, proprietary flags, and remediation pressure are grouped into an evidence-first risk surface."
      tone="red"
    >
    <div className="space-y-6">
      <section className="command-panel p-6">
        <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-center">
          <div>
            <p className="telemetry-label">{usingDemoData ? "demo fallback" : latestRun.runId}</p>
            <h1 className="mt-2 text-4xl font-semibold">Risk & Compliance</h1>
            <p className="mt-3 max-w-2xl text-sm text-muted-foreground">
              The latest run is converted into a lightweight policy matrix covering approved primitives, deprecated algorithms, and remediation pressure.
            </p>
          </div>
          <div className="flex flex-wrap gap-3">
            <Button
              className="cyber-button"
              onClick={() => downloadJson(`blackboxai-${latestRun.runId}-compliance.json`, exportPayload)}
            >
              <FileJson className="mr-2 h-4 w-4" />
              Export JSON
            </Button>
            <Button variant="outline" className="border-white/15">
              <Download className="mr-2 h-4 w-4" />
              PDF stub
            </Button>
          </div>
        </div>
      </section>

      <section className="grid gap-4 md:grid-cols-3">
        <div className={cn("command-panel border p-5", `risk-${latestRun.summary.riskLevel}`)}>
          <Shield className="mb-4 h-6 w-6" />
          <p className="telemetry-label">overall risk</p>
          <p className="metric-number mt-2">{latestRun.summary.riskScore}</p>
          <Progress className="mt-4" value={latestRun.summary.riskScore} />
        </div>
        <div className="success-panel p-5">
          <CheckCircle2 className="mb-4 h-6 w-6" />
          <p className="telemetry-label">policy pass rate</p>
          <p className="metric-number mt-2">{passRate}%</p>
          <Progress className="mt-4" value={passRate} />
        </div>
        <div className="danger-panel p-5">
          <AlertTriangle className="mb-4 h-6 w-6" />
          <p className="telemetry-label">algorithms at risk</p>
          <p className="metric-number mt-2">{atRisk}</p>
          <p className="mt-3 text-sm text-muted-foreground">{latestRun.input.filename}</p>
        </div>
      </section>

      <section className="command-panel overflow-hidden">
        <div className="border-b border-white/10 p-5">
          <p className="telemetry-label">compliance matrix</p>
        </div>
        <Table>
          <TableHeader>
            <TableRow className="border-white/10 hover:bg-transparent">
              <TableHead>Algorithm</TableHead>
              <TableHead>NIST</TableHead>
              <TableHead>FIPS 140-3</TableHead>
              <TableHead>Deprecated</TableHead>
              <TableHead>In Use</TableHead>
              <TableHead>Risk</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {rows.map((item) => (
              <TableRow key={item.algorithm} className="border-white/10 hover:bg-white/[0.04]">
                <TableCell className="font-medium">{item.algorithm}</TableCell>
                <TableCell>
                  <Status value={item.nistApproved} />
                </TableCell>
                <TableCell>
                  <Status value={item.fipsReady} />
                </TableCell>
                <TableCell>
                  <Status value={item.deprecated} inverted />
                </TableCell>
                <TableCell>
                  <Status value={item.inUse} />
                </TableCell>
                <TableCell>
                  <Badge className={cn("border font-mono uppercase", `risk-${item.riskLevel}`)}>{item.riskLevel}</Badge>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </section>

      <section className="grid gap-6 xl:grid-cols-[0.9fr_1.1fr]">
        <div className="command-panel p-5">
          <p className="telemetry-label">risk distribution</p>
          <div className="mt-6 space-y-5">
            {categories.map((category) => (
              <div key={category.label}>
                <div className="mb-2 flex items-center justify-between text-sm">
                  <span>{category.label}</span>
                  <span className="font-mono text-muted-foreground">{category.value}%</span>
                </div>
                <div className="h-2 overflow-hidden rounded-full bg-white/10">
                  <div
                    className="h-full rounded-full bg-gradient-to-r from-emerald-300 via-amber-300 to-red-400"
                    style={{ width: `${Math.min(100, Math.max(0, category.value))}%` }}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="command-panel p-5">
          <div className="flex items-center justify-between gap-4">
            <p className="telemetry-label">recommendations</p>
            <label className="flex items-center gap-2 font-mono text-xs uppercase text-muted-foreground">
              <Checkbox checked={includeEvidence} onCheckedChange={(checked) => setIncludeEvidence(Boolean(checked))} />
              Evidence appendix
            </label>
          </div>
          <div className="mt-5 space-y-3">
            {recommendations.map((rec) => (
              <div key={rec.id} className="rounded-md border border-white/10 bg-white/[0.03] p-4">
                <div className="flex items-start justify-between gap-3">
                  <h3 className="font-semibold">{rec.title}</h3>
                  <Badge className={cn("border font-mono uppercase", rec.priority === "High" ? "risk-high" : rec.priority === "Medium" ? "risk-medium" : "risk-low")}>
                    {rec.priority}
                  </Badge>
                </div>
                <p className="mt-2 text-sm text-muted-foreground">{rec.detail}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
    </NoirToolShell>
  );
};

export default RiskCompliance;
